#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/atlantis.yaml"
TERRAFORM_VERSION="v1.11.4"
STACKS=(audit baseline identity network platform)

cat > "${OUTPUT_FILE}" << 'EOF'
version: 3

# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by: scripts/generate-atlantis-yaml.sh
# To regenerate: make generate-atlantis

automerge: false
parallel_plan: true
parallel_apply: false

projects:
EOF

for stack in "${STACKS[@]}"; do
  workspace_dir="${REPO_ROOT}/${stack}/workspaces"

  if [[ ! -d "${workspace_dir}" ]]; then
    echo "Warning: ${workspace_dir} does not exist, skipping ${stack}" >&2
    continue
  fi

  stack_upper=$(echo "${stack}" | tr '[:lower:]' '[:upper:]')
  echo "  # ${stack_upper} STACK" >> "${OUTPUT_FILE}"

  for workspace_file in "${workspace_dir}"/*.yaml; do
    [[ -e "${workspace_file}" ]] || continue

    workspace=$(basename "${workspace_file}" .yaml)
    project_name="${stack}-${workspace}"

    cat >> "${OUTPUT_FILE}" << EOF
  - name: ${project_name}
    dir: ${stack}
    workspace: ${workspace}
    terraform_version: ${TERRAFORM_VERSION}
    autoplan:
      when_modified: ["*.tf", "workspaces/${workspace}.yaml"]
      enabled: true
    apply_requirements: [approved, mergeable, undiverged]
    workflow: default

EOF
  done
done

# Add workflow definition
cat >> "${OUTPUT_FILE}" << 'EOF'
workflows:
  default:
    plan:
      steps:
        - env:
            name: WORKSPACE
            command: 'echo $WORKSPACE'
        - init
        - plan
    apply:
      steps:
        - apply
EOF

echo "Generated ${OUTPUT_FILE}"
